<!doctype html>
<html>
<?php
$include_param = array(
'title'=>'答案窝-我的练习册',
'keyword'=>'答案窝 日语 我的练习册',
'description'=>'答案窝 日语 我的练习册',
);
include_once ROOT_PATH . 'application/layout/htmlhead.inc'; 
?>
<script type="text/javascript">
profilevalidate();
</script>
<body>
    <nav id="dark">
    	<div class="ym-wrapper">
            <div class="ym-wbox ym-clearfix">
                <ul>
                  <li><a href="http://www.answerwo.com/q/search">搜索</a></li>
                  <li><a href="http://www.answerwo.com/q/list">题库</a></li>
                  <li><a href="http://www.answerwo.com/q/practice">自由做题</a></li>                
                </ul>
                <?php include_once ROOT_PATH . 'application/layout/user.inc'; ?> 
            </div>
        </div>
    </nav>

    <header id="blue">
    	<div class="ym-wrapper">
            <div class="ym-wbox ym-clearfix">
                <div class="logo"><a href="http://www.answerwo.com"><img src="http://www.answerwo.com/public/images/logo.gif" width="313" height="35" alt="答案窝" /></a></div>
                <form class="ym-clearfix" method="get" action="http://www.answerwo.com/q/search">
                    <input name="query" type="search" placeholder="输入关键字搜索" class="inpmain" />
                    <input type="submit" value="搜索" class="inpsearch" />                
                </form>                
            </div>
        </div>
    </header>
    
   <?php include_once ROOT_PATH . 'application/layout/profileheader.inc'; ?> 
    
    <div id="main" class="list">
    	<div class="ym-wrapper" id="LIST">
            <div class="ym-wbox">
                <div class="ym-grid">
                    <div class="ym-g62-new ym-gl-new">
                        <div class="ym-gbox">
                        <form method="get" name="form" id="form">
                        <input type="hidden" name="removeid" value="" />
                        <input type="hidden" name="user" value="<?php if(isset($this->curuser)) {echo $this->curuser;}?>" />
                            <div class="list-info">我的练习册共有<?php echo isset($this->count) ? $this->count : "0";?>个</div>
                          	<div id="ListItems" class="list-items">
                          		<?php
                          			if(isset($this->result)) {
										$arr = Zend_Json::decode($this->result);
										if(!empty($arr)) { 
											foreach($arr as $val) {
                          		?>
                                <div class="list-item ym-clearfix ListItem">
                                    <div class="float"><i></i></div>                                
                                    <div class="float-clear"></div><!--尼玛IE6和IE7逼着我多写一个空标签-->
                                    <div class="content">
                                        <p><a href="<?php echo $val["link"];?>" target="_blank"><?php echo $val["createTime"];?>, 一共做了<?php echo $val["count"];?>道题</a></p>
                                    </div>
                                </div>
                                <?php
                                			}
                                		}
                                	} 
                                ?>
                            </div>
                            <div class="sh-page ym-clearfix" id="ListPager" page-total="45"></div>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
  <?php include_once ROOT_PATH . 'application/layout/footer.inc';?>

</body>
</html>