<!doctype html>
<html>
<?php
$include_param = array(
'title'=>'答案窝-修改密码',
'keyword'=>'答案窝 日语 修改密码',
'description'=>'答案窝 日语 修改密码',
);
include_once ROOT_PATH . 'application/layout/htmlhead.inc'; 
?>
<script type="text/javascript">
profilevalidate();
</script>
<body>
    <nav id="dark">
    	<div class="ym-wrapper">
            <div class="ym-wbox ym-clearfix">
                <ul>
                  <li><a href="http://www.answerwo.com/q/search">搜索</a></li>
                  <li><a href="http://www.answerwo.com/q/list">题库</a></li>
                  <li><a href="http://www.answerwo.com/q/practice">自由做题</a></li>                
                </ul>
                <?php include_once ROOT_PATH . 'application/layout/user.inc'; ?> 
            </div>
        </div>
    </nav>

    <header id="blue">
    	<div class="ym-wrapper">
            <div class="ym-wbox ym-clearfix">
                <div class="logo"><a href="http://www.answerwo.com"><img src="http://www.answerwo.com/public/images/logo.gif" width="313" height="35" alt="答案窝" /></a></div>
                <form class="ym-clearfix" method="get" action="http://www.answerwo.com/q/search">
                    <input name="query" type="search" placeholder="输入关键字搜索" class="inpmain" />
                    <input type="submit" value="搜索" class="inpsearch" />                
                </form>                
            </div>
        </div>
    </header>
    
   <?php include_once ROOT_PATH . 'application/layout/profileheader.inc'; ?> 
    
    <div id="main" class="list">
    	<div class="ym-wrapper" id="LIST">
            <div class="ym-wbox">
                <div class="ym-grid">
                    <div class="ym-g62-new ym-gl-new">
                        <div class="ym-gbox">
                        <?php if(isset($this->information)) {?>
                        <span><?php echo $this->information;?></span>
                        <?php } else {?>
                        <form method="post" name="form" id="form" class="ztm-form">
	                        <input type="hidden" name="removeid" value="" />
	                        <input type="hidden" name="user" value="<?php if(isset($this->curuser)) {echo $this->curuser;}?>" />
	                        <div class="item">
                        		<label class="title">新密码: </label>
                            	<input type="password" maxlength="30" minlength="2" name="password" class="inp-new">
                        	</div>
	              			<div class="item">
                        		<label class="title">新密码确认: </label>
                            	<input type="password" maxlength="30" minlength="2" name="repassword" class="inp-new">
                        	</div>
	                        <button type="submit" class="btn">确认</button>  	
	                        <div class="sh-page ym-clearfix" id="ListPager" page-total="45"></div>
                        </form>
                        <?php }?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
  <?php include_once ROOT_PATH . 'application/layout/footer.inc';?>

</body>
</html>