<!doctype html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>答案窝-创建索引</title>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <!-- mobile viewport optimisation -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- stylesheets -->
    <link rel="stylesheet" href="https://test.answerwo.com/public/css/zhaotimu.css" type="text/css"/>
    <!--[if lte IE 7]>
    <link rel="stylesheet" href="https://test.answerwo.com/public/css/ym-iehacks.min.css" type="text/css"/>
    <![endif]-->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
<?php echo "成功创建".$this->total."道题目!";?>
</body>
</html>