<footer>
	<div class="ym-wrapper">
		<div class="ym-wbox">
			<ul class="ym-clearfix">
				<li class="nostyle"><a href="http://www.answerwo.com/s/aboutus" target="_blank">关于我们</a></li>
				<li><a href="http://www.answerwo.com/s/announcement" target="_blank">免责声明</a></li>
				<li><a href="http://www.answerwo.com/s/copyright" target="_blank">版权声明</a></li>
				<li><a href="http://www.answerwo.com/s/contact" target="_blank">联系我们</a></li>
				<li><a href="http://www.answerwo.com/s/map" target="_blank">网站地图</a></li>
			</ul>
			<p>答案窝网站希望发动所有的同学来共同建设最高质量的日语题库，为大家一起提升日语水平</p>
			<p>本站的全部文字在<a href="http://www.answerwo.com/s/protocal" target="_blank">知识共享 署名-相同方式共享3.0协议</a>之条款下提供，附加条款亦可使用（请参阅<a href="http://www.answerwo.com/s/additional" target="_blank">使用条款</a>）</p>
			<p>© 2012 答案窝网站保留所有权利 </p>
		</div>
	</div>
</footer>

<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F92151da7e610ead3bd6f8103b48fd469' type='text/javascript'%3E%3C/script%3E"));
</script>