<!doctype html>
<html>
<?php
$include_param = array(
       				 'title'=>'答案窝-首页',
        			 'keyword'=>'答案窝 日语 等级考试 答案窝首页',
					 'description'=>'答案窝 答案窝首页',
    				 ); 
include_once ROOT_PATH . 'application/layout/htmlhead.inc'; 
?>
<body>

    <div id="main" style="background-image:none; background-color:#fff;">
        <div class="wrapper">
            <div class="home-title"><img src="http://www.answerwo.com/public/images/home_title.gif" width="980" height="43" alt="找题目"></div>
            <div class="home-tiles ym-clearfix">
                <div class="sh-tile sh-tile-t12 sh-tile-blue">
                	<a class="sh-tile-bigicon" href="#">
                    	<i class="sh-tile-icon-physics"></i>
                        <b>历年真题</b>
                    </a>
                </div>
                <div class="sh-tile sh-tile-t11 sh-tile-green">
                    <a class="sh-tile-normal" href="http://www.answerwo.com/q/search"><b>强大题库</b><span>100000题</span></a>
                </div>
                <div class="sh-tile sh-tile-t11 sh-tile-blue">
                	<a class="sh-tile-smallicon" href="#">
                    	<i class="sh-tile-icon-world"></i>
                        <span>做题PK</span>
                    </a>
                </div>
                <div class="sh-tile sh-tile-t11 sh-tile-green">
                    <a class="sh-tile-normal" href="#"><b>完美解析</b><span>自定义解析</span></a>
                </div>
                <div class="sh-tile sh-tile-t11 sh-tile-red sh-tile-right">
                    <a class="sh-tile-normal" href="#"><b>题目收藏</b><span>定制自己的题库</span></a>
                </div>
                <div class="sh-tile sh-tile-t11 sh-tile-yellow">
                    <a class="sh-tile-mid" href="#">
                    	<span>日语真题：<br />強盗がその老人を...</span>
                    	<i class="sh-tile-icon-ce"></i>
                    </a>
                </div>
                <div class="sh-tile sh-tile-t13 sh-tile-search"></div>
                <div class="sh-tile sh-tile-t22 sh-tile-blue sh-tile-right">
                    <a href="#" class="sh-tile-img">
                        <img src="http://www.answerwo.com/public/images/home_temp.gif" width="316" height="245">
                        <b>模拟练习 ></b>
                    </a>
                </div>
                <div class="sh-tile sh-tile-t21 sh-tile-green sh-tile-up1">
                	<a class="sh-tile-bigicon" href="#">
                    	<i class="sh-tile-icon-hat"></i>
                        <span>敬语用法的详细解答...</span>
                    </a>
                </div>
                <div class="sh-tile sh-tile-t11 sh-tile-yellow sh-tile-up1">
                    <a class="sh-tile-mid" href="#">
                    	<span>2012年7月一级真题</span>
                    	<i class="sh-tile-icon-zhen"></i>
                    </a>
                </div>
                <div class="sh-tile sh-tile-t12 sh-tile-red sh-tile-up1 sh-tile-left1">
                    <a class="sh-tile-mid" href="#">
                    	<span>日语等级考试一级必考知识点...</span>
                    	<i class="sh-tile-icon-bi"></i>
                    </a>
                </div>
                <div class="sh-tile sh-tile-t12 sh-tile-blue">
                  <a class="sh-tile-headline" href="#">JTest ></a>
                </div>
                <div class="sh-tile sh-tile-t11 sh-tile-green">
                  <a class="sh-tile-normal" href="#"><b>JTest精选</b><span>100000题</span></a>
                </div>
                <div class="sh-tile sh-tile-t11 sh-tile-blue">
                    <a class="sh-tile-mid" href="#">
                    	<span>2011年12月真题解答</span>
                    	<i class="sh-tile-icon-jie"></i>
                    </a>
                </div>
                <div class="sh-tile sh-tile-t11 sh-tile-yellow sh-tile-right">
                	<a class="sh-tile-smallicon" href="#">
                    	<i class="sh-tile-icon-pen"></i>
                        <span>在线模拟测试</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    
<?php include_once ROOT_PATH . 'application/layout/footer.inc';?>
</body>
</html>
