<!doctype html>
<html>
<?php
$include_param = array(
'title'=>'答案窝-个人中心',
'keyword'=>'答案窝 日语 个人中心',
'description'=>'答案窝 日语 个人中心',
);
include_once ROOT_PATH . 'application/layout/htmlhead.inc'; 
?>
<script type="text/javascript">
profilevalidate();
</script>
<body>
    <nav id="dark">
    	<div class="ym-wrapper">
            <div class="ym-wbox ym-clearfix">
                <ul>
                  <li><a href="http://prepublish.answerwo.com/q/search">搜索</a></li>
                  <li><a href="http://prepublish.answerwo.com/q/list">题库</a></li>
                  <li><a href="http://prepublish.answerwo.com/q/practice">自由做题</a></li>                
                </ul>
                <?php include_once ROOT_PATH . 'application/layout/user.inc'; ?> 
            </div>
        </div>
    </nav>

    <header id="blue">
    	<div class="ym-wrapper">
            <div class="ym-wbox ym-clearfix">
                <div class="logo"><a href="http://prepublish.answerwo.com"><img src="http://prepublish.answerwo.com/public/images/logo.gif" width="313" height="35" alt="答案窝" /></a></div>
                <form class="ym-clearfix" method="get" action="http://prepublish.answerwo.com/q/search">
                    <input name="query" type="search" placeholder="输入关键字搜索" class="inpmain" />
                    <input type="submit" value="搜索" class="inpsearch" />                
                </form>                
            </div>
        </div>
    </header>
    
   <?php include_once ROOT_PATH . 'application/layout/profileheader.inc'; ?> 
    
    <div id="main" class="list">
    	<div class="ym-wrapper" id="LIST">
            <div class="ym-wbox">
                <div class="ym-grid">
                    <div class="ym-g62-new ym-gl-new">
                        <div class="ym-gbox">
                        <form method="get" name="form" id="form">
                        <input type="hidden" name="removeid" value="" />
                        <input type="hidden" name="user" value="<?php if(isset($this->curuser)) {echo $this->curuser;}?>" />
                            <div class="list-info">我的动态</div>
                          	<div id="ListItems" class="list-items">
                          		<?php
                          			if(isset($this->questions)) {
										$arr = Zend_Json::decode($this->questions);
										if(!empty($arr)) { 
											foreach($arr as $key=>$val) {
                          		?>
                                <div class="list-item ym-clearfix ListItem">
                                    <div class="float"><i></i></div>                                
                                    <div class="float-clear"></div><!--尼玛IE6和IE7逼着我多写一个空标签-->
                                    <div class="content">
                                        <p><a href="<?php echo $val["link"];?>" target="_blank">
                                        <?php 
                                		if(strlen($val["question"]) > 140) {
											$i = 140;
											for(; $i < strlen($val["question"]); $i++) {
												if(ord($val["question"][$i]) < 100) {
													break;
												}
											}
											echo substr($val["question"],0,$i)."..."; 
										}
										else {
											echo $val["question"];
										}
										if(isset($val["content"])) {
											if(strlen($val["content"]) > 100) {
												$i = 100;
												for(; $i < strlen($val["content"]); $i++) {
													if(ord($val["content"][$i]) < 100) {
														break;
													}
												}
												$val["content"] = substr($val["content"],0,$i)."...";
											}
										}
                                	?>
                                        </a></p><div class="right-new"><?php echo $val["createTime"];?></div>
                                        <?php if($val["type"] == "favorite") {?>
                                        <span><?php echo $val["year"];?>考题，难度<?php echo $val["difficulty"];?>，<?php echo $val["explaincount"]?>解答，<?php echo $val["discusscount"]?>评论，<?php echo $val["favoritecount"];?>人收藏</span><br>
                                        <span style="color: #222222;text-decoration: none;">我的收藏</span>
										<?php } elseif($val["type"] == "explain") {?>
										<span><?php echo $val["year"];?>考题，难度<?php echo $val["difficulty"];?>，<?php echo $val["explaincount"]?>解答，<?php echo $val["discusscount"]?>评论，<?php echo $val["favoritecount"];?>人收藏</span><br>
                                        <span style="color: #222222;text-decoration: none;">我的解析: <?php echo $val["content"];?></span>
										<?php } elseif($val["type"] == "discuss") {?>
										<span><?php echo $val["year"];?>考题，难度<?php echo $val["difficulty"];?>，<?php echo $val["explaincount"]?>解答，<?php echo $val["discusscount"]?>评论，<?php echo $val["favoritecount"];?>人收藏</span><br>
                                        <span style="color: #222222;text-decoration: none;">我的讨论: <?php echo $val["content"];?></span>
										<?php } elseif($val["type"] == "record") {?>
										<span><?php echo $val["year"];?>考题，难度<?php echo $val["difficulty"];?>，正确答案<?php echo $val["correctanswer"];?>，<?php echo $val["explaincount"]?>解答，<?php echo $val["discusscount"]?>评论，<?php echo $val["favoritecount"];?>人收藏</span><br>
                                        <span style="color: #222222;text-decoration: none;">我的答案: <?php echo $val["answer"];?></span>
										<?php }?>
                                    </div>
                                </div>
                                <?php
                                			}
                                		}
                                	} 
                                ?>
                            </div>
                            <div class="sh-page ym-clearfix" id="ListPager" page-total="45"></div>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
  <?php include_once ROOT_PATH . 'application/layout/footer.inc';?>

</body>
</html>