			<div class="ym-g25 ym-gr">
                    	<div class="ym-gbox">
                    		<ul class="about-siderbar">
                            	<li class="sh-tile-blue">
                                	<a href="http://www.answerwo.com/s/aboutus" class="ym-clearfix">
                                    	<i class="about-icon-abouticon"></i>
                                        <span>关于我们</span>
                                    </a>
                                </li>
                                
                            	<li class="sh-tile-yellow">
                                	<a href="http://www.answerwo.com/s/contact" class="ym-clearfix">
                                    	<i class="about-icon-contact"></i>
                                        <span>联系我们</span>
                                    </a>
                                </li>
                                
                            	<li class="sh-tile-gray">
                                	<a href="http://www.answerwo.com/s/copyright" class="ym-clearfix">
                                    	<i class="about-icon-fback"></i>
                                        <span>版权声明</span>
                                    </a>
                                </li>
                                
                                 <li class="sh-tile-red">
                                	<a href="http://www.answerwo.com/s/announcement" class="ym-clearfix">
                                    	<i class="about-icon-clamer"></i>
                                        <span>免责声明</span>
                                    </a>
                                </li>
                                <!-- <li class="about-tile-gray"> -->
                                <li class="sh-tile-green">
                                	<a href="http://www.answerwo.com/s/map" class="ym-clearfix">
                                    	<i class="about-icon-map"></i>
                                        <span>网站地图</span>
                                    </a>
                                </li>
                            </ul>
                      </div>
                    </div>