<nav id="blue" class="ym-wrapper">
        <div class="ym-wbox">
            <div class="ym-grid">
                <div class="ym-g20 ym-gl">
                    <div class="ym-gbox">
                        <a class="subject-current" href="#">初中数学</a>
                        <ul class="subject">
                            <li><a href="#">初中语文</a></li>
                            <li><a href="#">初中英语</a></li>
                            <li><a href="#">初中物理</a></li>
                        </ul>
                    </div>
                </div>
                <div class="ym-g80 ym-gr">
                    <div class="ym-gbox">
                        <ul class="naviga">
                          <li><a href="/profile/favorite">收藏夹</a></li>
                          <li><a href="/profile/mysheet">题目清单</a></li>
                          <li><a href="/profile/mycontribution">我的贡献</a></li>
                        </ul>
                        <div class="action"><a href="#">导出题目</a></div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
