    <div class="po-share Popup" title="马上分享这个题目给朋友：" popup-id="share" popup-width="330" popup-effect="slide" popup-stick="righttop" popup-title="other">
        <!-- JiaThis Button BEGIN -->
        <div id="jiathis_style_32x32" class="ym-clearfix">
            <a class="jiathis_button_qzone"></a>
            <a class="jiathis_button_tsina"></a>
            <a class="jiathis_button_tqq"></a>
            <a class="jiathis_button_renren"></a>
            <a class="jiathis_button_douban"></a>
            <a class="jiathis_button_kaixin001"></a>
            <a class="jiathis_button_copy"></a>
            <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jiathis_separator jtico jtico_jiathis" target="_blank"></a>
        </div>
        <script type="text/javascript" >var jiathis_config={summary:"",hideMore:true}</script>
        <script type="text/javascript" src="http://v2.jiathis.com/code/jia.js" charset="utf-8"></script>
        <!-- JiaThis Button END -->
    </div>