	<div class="po-favorite Popup" id="FavoriteTagDetail" title="题目收藏成功！" popup-id="favoritedetail" popup-width="330" popup-effect="slide" popup-stick="righttop" popup-title="other">
        <p>你还可以通过添加标签来管理收藏的题目</p>
        <div class="title">标签：<span class="gary">（多个标签用英文逗号隔开）</span></div>
        <input type="text" tagger-id="123456789">
        <div class="title">常用标签：</div>
        <div class="link ym-clearfix">
            <a href="javascript:void(0)">某个标签</a>
            <a href="javascript:void(0)">标签</a>
            <a href="javascript:void(0)">个标签</a>
            <a href="javascript:void(0)">某标签</a>
            <a href="javascript:void(0)">某签</a>
            <a href="javascript:void(0)">某个标签</a>
            <a href="javascript:void(0)">标签</a>
            <a href="javascript:void(0)">某个标签</a>
            <a href="javascript:void(0)">某签</a>
            <a href="javascript:void(0)">标签</a>
        </div>
        <button class="fo-btn" ajax="FavoriteTag">保存标签</button>
    </div>