<!doctype html>
<html>
<head>
<meta charset="utf-8"/>
<title>答案窝-疑似爬虫页面</title>    
<meta property="wb:webmaster" content="9b15163589206cb0" />
<meta property="qc:admins" content="556777151346163752776375" />
<meta name="keyword" content="答案窝 日语 等级考试 疑似爬虫页面"/>
<meta name="description" content="答案窝 疑似爬虫页面"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="http://www.answerwo.com/public/css/answerwo.css" type="text/css"/>
</head>
<body class="body-error">
<body>
  <a href="//www.answerwo.com/">答案窝</a>
  <image alt="答案窝" src="http://www.answerwo.com/public/images/robot.png" class="body-error-img2">
  <p><ins>对不起，您的操作疑似网络蜘蛛，请稍后再访问，谢谢！</ins></p>
</body>
</html>
