<!doctype html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>答案窝-题目创建</title>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <!-- mobile viewport optimisation -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- stylesheets -->
    <link rel="stylesheet" href="https://test.answerwo.com/public/css/zhaotimu.css" type="text/css"/>
    <!--[if lte IE 7]>
    <link rel="stylesheet" href="https://test.answerwo.com/public/css/ym-iehacks.min.css" type="text/css"/>
    <![endif]-->
    <!--[if lt IE 9]>
    <script src="https://test.answerwo.com/public/js/google.html5.js"></script>
    <![endif]-->
    <script type="text/javascript" src="https://test.answerwo.com/public/js/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="https://test.answerwo.com/public/js/zhaotimu.plugins.js"></script>
	<script type="text/javascript" src="https://test.answerwo.com/public/js/zhaotimu.js"></script>
</head>
<body>

     <nav id="dark">
    	<div class="ym-wrapper">
             <div class="ym-wbox ym-clearfix">
                <ul>
                  <li class="current">题目创建</li>
                  <li><a href="#">题目编辑</a></li>
                  <li><a href="#">题目删除</a></li>
                  <li><a href="#">用户管理</a></li>
                </ul>
                <div class="userinfo">
                    <a href="#">登录</a>
                    <a href="#" class="important">新用户注册</a>
                </div>
            </div>
        </div>
    </nav>

    <header id="blue">
    	<div class="ym-wrapper">
            <div class="ym-wbox ym-clearfix">
                <div class="logo"><a href="#"><img src="https://test.answerwo.com/public/images/logo.gif" width="313" height="35" alt="答案窝" /></a></div>
                <a href="#" class="add">新增</a>
                <form class="ym-clearfix">
                    <input type="search" placeholder="输入关键字搜索" class="inpmain" />
                    <input type="submit" value="搜索" class="inpsearch" />                
                </form>                
            </div>
        </div>
    </header>
    
    <div id="crumb">
    	<div class="ym-wrapper">
            <div class="ym-wbox">
                <div class="ym-grid">
                    <div class="ym-g85 ym-gl">
                        <div class="ym-gbox">
                            <h1>创建题目</h1>
                            <div class="fliter">让我们一起来打造最全的日语题库，帮助更多的朋友！</div>
                        </div>
                    </div>
                    <div class="ym-g15 ym-gr">
                        <div class="ym-gbox">
                            <div class="more"><a href="#">创建题目的帮助说明</a></div> 
                        </div>
                    </div>
                </div>            	
            </div>
        </div>
    </div>
    
    <div id="main">
    	<div class="ym-wrapper">
            <div class="ym-wbox">
                <div class="ym-grid">
                    <div class="ym-g62 ym-gl">
                        <div class="ym-gbox">
                            <form class="ztm-form" id="FormRegister" method=post>
                            	<div class="item">
                                	<label class="title">题目内容<sup>*</sup></label>
                                    <textarea cols=100 rows=6 name="content" value=""></textarea>
                                </div>
                                <div class="item">
                                	<label class="title">答案1</label>
                                    <textarea cols=100 rows=3 name="answer1"></textarea>
                                </div>
                                <div class="item">
                                	<label class="title">答案2</label>
                                    <textarea cols=100 rows=3 name="answer2"></textarea>
                                </div>
                                <div class="item">
                                	<label class="title">答案3</label>
                                    <textarea cols=100 rows=3 name="answer3"></textarea>
                                </div>
                                <div class="item">
                                	<label class="title">答案4</label>
                                    <textarea cols=100 rows=3 name="answer4"></textarea>
                                </div>
                                <div class="item">
                                	<label class="title">题目答案</label>
                                    <input type="text" class="inp" size=100 name="answer" />
                                </div>
                                <div class="item">
                                	<label class="title">题目考点(文法，词汇，听力......)</label>
                                    <input type="text" class="inp" size=100 name="knowledge" value="文字"/>
                                </div>
                                <div class="item">
                                	<label class="title">题目来源(2001-1,2008-3,......)</label>
                                    <input type="text" class="inp" size=100 name="source" />
                                </div>
                                <div class="item">
                                	<label class="title">题目类型<sup>*</sup>(单选，双选，作文......)<a href="#" class="btn">题型对应关系</a></label>
                                    <!--  <input type="text" class="inp" size=100 name="type" value="2"/> --> 
                                    <select name="type" id="type">
                                    	<option value="1">单选题</option>
                                    	<option value="2">扩展单词全称</option>
                                    	<option value="3">缩短单词简称</option>
                                    	<option value="4">缩短意思简称</option>
                                    	<option value="5">表述最恰当</option>
                                    	<option value="6">意思相似表述</option>
                                    	<option value="7">阅读题</option>
                                    	<option value="8">听力题</option>
                                    </select>
                                </div>
                                <div class="item">
                                	<label class="title">题目解答</label>
                                    <textarea cols=100 rows=6 name="explain"></textarea>
                                </div>
                                <div class="item">
                                	<label class="title">题目难度</label>
                                    <ul class="radio radio-aline ym-clearfix">
                                    	<li><input type="radio" name="difficulty" value="1"/><label>很难</label></li>
                                        <li><input type="radio" name="difficulty" value="2"/><label>难</label></li>
                                        <li><input type="radio" name="difficulty" value="3"/><label>普通</label></li>
                                        <li><input type="radio" name="difficulty" value="4"/><label>简单</label></li>
                                        <li><input type="radio" name="difficulty" value="5"/><label>很简单</label></li>
                                    </ul>
                                </div>                           
                                <button type="submit" class="btn">创建</button>
                            </form>
                        </div>
                    </div>
                    <div class="ym-g38 ym-gr">
                        <div class="ym-gbox">
                            <div class="w-add">
                            	<b>你有大量的题目要提交给我们？</b>
                                <a href="#" class="btn">点击这里提交</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <?php include_once ROOT_PATH . 'application/layout/footer.inc';?>

</body>
</html>